### ISSUE TITLE
Duplicate /v2 applied on some files

### ISSUE THREAD

**Issue by johanbrandhorst** [marwan-at-work/mod#10]
Hi!

I tried running `mod` on the grpc-gateway project and it produced some strange imports on some of the files:

`examples/internal/server/echo.go`:
```go
package server

import (
	"context"

	"github.com/golang/glog"
	examples "github.com/grpc-ecosystem/grpc-gateway/v2/v2/examples/internal/proto/examplepb"
	"google.golang.org/grpc"
	"google.golang.org/grpc/metadata"
)
```

This happened to a few of them, but we also got some even more interesting imports:
`runtime/errors.go`:
```go
package runtime

import (
	"context"
	"io"
	"net/http"

	"github.com/grpc-ecosystem/grpc-gateway/v2/v2/v2/internal"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/grpclog"
	"google.golang.org/grpc/status"
)
```

Steps to reproduce:
1. Check out master of `grpc-gateway`:
   ```shell
   $ git clone git@github.com:grpc-ecosystem/grpc-gateway.git
   ```
1. Run `mod upgrade`
   ```shell
   $ mod upgrade
   ```

**Comment by marwan-at-work** [comment]
@johanbrandhorst hey 👋 

Thanks for the catch :) 

I just fixed this [here](https://github.com/marwan-at-work/mod/commit/1cfae61c938befc44ceb7d40253c8241259b7738) and it seems to remove the issue.

Would love it if you can give it a try and let me know if it's working on your side. 

More context: it looks like the `./...` pattern for go/packages is loading multiple packages twice [here](https://github.com/marwan-at-work/mod/blob/master/major/major.go#L42), which is probably worth raising upstream. For now, I just ensured we don't process the same file twice.

**Comment by johanbrandhorst** [comment]
@marwan-at-work hey :wave: :heart_eyes:!

That seems to have fixed it, thanks!
