### ISSUE TITLE
please update installation instructions for Go 1.17 and later

### ISSUE THREAD

**Issue by thediveo** [marwan-at-work/mod#15]
First, many thanks for your tool, as it helped me several times not only to upgrade some of my own packages from v0 to v2, but also dependencies from v1->v2, v3->v4, et cetera. Much better, more reliably, and less headaches than Ctrl-Shift-H (global replace) in VSCode.

The installation instructions in `README.md` are becomming outdated, as of Go 1.17 `go get` warns and of 1.18 blocks installation from Go modules. Please update the documentaion to use `go install ...@latest`.

**Comment by marwan-at-work** [comment]
Glad you found it helpful, and appreciate the issue to keep the instructions up to date. I've updated the README but let me know if anything else is missing. Thanks

**Comment by thediveo** [comment]
Works as said on the tin! The tool Goggle should have released a part of 1.13 modules.
