### ISSUE TITLE
Unexpected downgrade

### ISSUE THREAD

**Issue by blampe** [marwan-at-work/mod#28]
Repro is [here](https://github.com/blampe/mod-downgrade/commits/main/).

Start with a baseline of two dependencies both at v3.141.0.

Run this command (as provided by Renovate):
```
go run github.com/marwan-at-work/mod/cmd/mod@latest upgrade --mod-name=github.com/pulumi/pulumi/pkg/v3 -t=3
```

Observe the `github.com/pulumi/pulumi/pkg/v3` dependency is downgraded to `v3.131.0`.

I would expect this to no-op, since `v3.141` is the latest release and there are no imports to re-write.

I've observed this behavior locally as well as on a self-hosted Renovate instance configured with `"postUpdateOptions": ["gomodUpdateImportPaths"]`.

Omitting `"gomodUpdateImportPaths"` prevents the downgrade.

**Comment by blampe** [comment]
I agree #29 looks like it will help. I might also suggest an option to skip the `tidy` altogether, so if something external like Renovate is already handling `go.mod` you won't end up overwriting it. From what I gather, Renovate primarily uses `mod` to help re-write imports but doesn't expect it to modify the dependencies. I could be wrong though!

**Comment by marwan-at-work** [comment]
@blampe yeah we could potentially let `-t` take a full version instead of just the major number. Happy to welcome a PR but otherwise might throw something in when i get the time. Thanks!

**Comment by blampe** [comment]
@marwan-at-work do you think we could get a release for this fix?
