### ISSUE TITLE
Tool for client code?

### ISSUE THREAD

**Issue by dolmen** [marwan-at-work/mod#5]
If I upgrade a library to a new major release using "mod", what tool exist to upgrade import paths in client code?

**Comment by dolmen** [comment]
There is another way which is builtin in Go toolchain: `go mod edit -require=<module>@<version> && go build && go mod tidy`. `<version>` can be `master` to use the latest code.

So I'm closing the issue.

**Comment by marwan-at-work** [comment]
@dolmen does that actually update the import paths of all `.go` files in the subtree?
