### ISSUE TITLE
Open source license

### ISSUE THREAD

**Issue by jayconrod** [marwan-at-work/mod#6]
Would you consider adding an open source license in a top-level LICENSE file? I'm guessing your intent is for this tool to be open source, but it doesn't look like that's explicitly written anywhere.

**Comment by marwan-at-work** [comment]
@jayconrod thank you for the note. I have added an MIT LICENSE file. Feel free to reopen the issue if anything else is missing.

**Comment by jayconrod** [comment]
Thanks! All looks good.
