### ISSUE TITLE
'package "XXX" without types was imported from' Error message

### ISSUE THREAD

**Issue by jonbodner** [marwan-at-work/mod#9]
Hello,

I'm not sure if I'm doing something wrong or if there's an incompatibility with Go 1.14 and this tool.

I installed with `go get github.com/marwan-at-work/mod/cmd/mod`

Steps to reproduce:

- git clone https://github.com/jonbodner/taxes
- cd taxes
- mod upgrade

Error occurs:
`2020/03/28 23:34:18 internal error: package "fmt" without types was imported from "github.com/jonbodner/taxes"`

Also tried on v2 subdirectory:
- cd v2
- mod upgrade

Error occurs:
`2020/03/28 23:37:57 internal error: package "errors" without types was imported from "github.com/jonbodner/taxes/v2"`

**Comment by marwan-at-work** [comment]
@jonbodner thank you for opening an issue 
I believe I just needed to upgrade an outdated dependenciy. 

I just pushed the upgrade to master [here](https://github.com/marwan-at-work/mod/commit/549dc8790e8dc5e6e36d6f39ae14d84523a7cac3)

Can you please re-install `mod` by running the following command:
`GO111MODULE=on go get github.com/marwan-at-work/mod/cmd/mod@master` 

OR `git clone https://github.com/marwan-at-work/mod && cd mod/cmd/mod && go install` 

and see if that fixes it, if so I'll cut a new release.

**Comment by jonbodner** [comment]
That seems to fix it, thanks!
